spring:
  application:
    name: 9diMeak

  # Database Configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/9diMeak_db
      auto-index-creation: true

  # Jackson (JSON) Configuration
  jackson:
    default-property-inclusion: non_null # Don't send null fields in JSON responses

# Server Configuration
server:
  port: 8080
  error:
    include-message: always

# Security Configuration
application:
  security:
    jwt:
      secret-key: {SECRET_KEY}
      expiration: 86400000 # in milliseconds
      issuer: 9diMeak-management-api

# Logging
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb: INFO
    com.logistics.system: DEBUG